spring:
  application:
    name: calendar-aggregator
  # Security configuration - can be overridden with profiles
  security:
    enabled: true

server:
  port: 8080

# Local development settings (can be overridden with --spring.profiles.active=local)
local:
  security:
    enabled: false
  debug: true

google:
  calendar:
    application-name: Calendar Aggregator
    credentials-file: ${GOOGLE_CREDENTIALS_FILE}
    scopes:
      - https://www.googleapis.com/auth/calendar

outlook:
  client-id: ${OUTLOOK_CLIENT_ID}
  client-secret: ${OUTLOOK_CLIENT_SECRET}
  tenant-id: ${OUTLOOK_TENANT_ID}
  scopes:
    - Calendars.ReadWrite
    - offline_access

logging:
  level:
    com.calendar: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Profile-specific configurations
---
spring:
  config:
    activate:
      on-profile: local
  security:
    enabled: false
  logging:
    level:
      com.calendar: DEBUG
      org.springframework.web: DEBUG
      org.springframework.security: DEBUG 