spring:
  application:
    name: calendar-aggregator
  # OAuth2 Client Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - https://www.googleapis.com/auth/calendar
              - https://www.googleapis.com/auth/calendar.events
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
          outlook:
            client-id: ${OUTLOOK_CLIENT_ID}
            client-secret: ${OUTLOOK_CLIENT_SECRET}
            redirect-uri: ${OUTLOOK_REDIRECT_URI}
            scope:
              - Calendars.ReadWrite
              - offline_access
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          outlook:
            authorization-uri: https://login.microsoftonline.com/${OUTLOOK_TENANT_ID}/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/${OUTLOOK_TENANT_ID}/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/v1.0/me
            user-name-attribute: id

server:
  port: 8080

# Local development settings (can be overridden with --spring.profiles.active=local)
local:
  security:
    enabled: false
  debug: true

google:
  calendar:
    application-name: ${GOOGLE_APPLICATION_NAME}
    credentials-file: ${GOOGLE_CREDENTIALS_FILE}
    scopes:
      - https://www.googleapis.com/auth/calendar

outlook:
  client-id: ${OUTLOOK_CLIENT_ID}
  client-secret: ${OUTLOOK_CLIENT_SECRET}
  tenant-id: ${OUTLOOK_TENANT_ID}
  scopes:
    - Calendars.ReadWrite
    - offline_access

logging:
  level:
    com.calendar: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Profile-specific configurations
---
spring:
  config:
    activate:
      on-profile: local
  security:
    enabled: false
  logging:
    level:
      com.calendar: DEBUG
      org.springframework.web: DEBUG
      org.springframework.security: DEBUG 